### ISSUE TITLE
[Bug] "Cannot import name 'format_ansi' from 'milc'"

### ISSUE THREAD

**Issue by cst0** [qmk/qmk_cli#108]
### Describe the Bug

Upon running any command using the QMK command line tool, I get the error:
```
ImportError: cannot import name 'format_ansi' from 'milc' (/home/cst/.local/lib/python3.8/site-packages/milc/__init__.py)
```
I tried getting QMK using:
- `apt` first, and although I successfully got an executable I saw that error.
- `pip` next, and I again got an executable but still saw that error.
-  Then, cloning directly and using `python -m build`, which worked but was local to the directory (causing `qmk setup` to fail, I suspect because `qmk` was not on my path).

As a workaround, I ran `python -m build --no-isolation`, which resolved the dependencies outside of a virtual environment. This allowed me to install via qmk and the tool is now working for me.

I'm running on Ubuntu 20.04, and my Python interpreter is Python 3.8.

**Comment by fauxpark** [comment]
You need to update your qmk_firmware repo.

**Comment by cst0** [comment]
The error I've included seems to be related to a system package not being available, which is why I think my workaround of installing system dependencies seems to have worked. I'm not sure how cloning the most recent version of the firmware repo would fix it, particularly given that I'm already using the most recent version of the master branch (because `qmk setup` is the command that clones it).

**Comment by fauxpark** [comment]
`qmk setup` may not do what you expect if you already have a qmk_firmware repo, although it should tell you that it found the repo.

There is Python code in both rhe CLI package and qmk_firmware; the error here is coming from the fact that the latter is expecting an older version of MILC which provides format_ansi. all three have since been updated to not need this, but it seems like your qmk_firmware, and possibly your CLI version, is not up to date.
