### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by judwal** [qmk/qmk_cli#140]
### Information

- [X] None of the other issue templates apply

### Description

Hæ

I try to build QMK for a **ARM64** architecture using **Docker** (official images are for amd64 in hub.docker).
During the building of « qmk_cli », using Dockerfile and the command « **sudo docker build -t  qmkfm/qmk_cli  .** » an error is raised :

> Step 2/5 : ADD dist /tmp/dist
> ADD failed: file not found in build context or excluded by .dockerignore: stat dist: file does not exist

There is no « dist(tribution/ant ?) » directory in the source code of qmk_cli.

Where am I wrong ?

Thanks for your help.

**Comment by judwal** [comment]
What a pity, there is no workaround ? With using another library ? ( previous release did well with arm64 architecture - with build of qmk_base_container + qmk_firmware)

**Comment by tzarc** [comment]
The issue is a lack of suitable prebuilt toolchain for gcc 8.x on aarch64.
I struck the same problem when attempting to move some builds to Pi4's -- non-trivial solution that necessitates building an entire toolchain.

There are ideas being tossed around regarding providing a set toolchain version across all architectures, but there's a lot of legwork to get there.

**Comment by zvecr** [comment]
ARM images published.

For manualy building, you would need to download the cli files manually like <https://github.com/qmk/qmk_cli/blob/master/.github/workflows/docker-republish.yml#L33>.

**Comment by tsujp** [comment]
> ARM images published.
> 
> For manualy building, you would need to download the cli files manually like https://github.com/qmk/qmk_cli/blob/master/.github/workflows/docker-republish.yml#L33.

Aren't those artifacts for macOS aarch64 only? What about Linux as a host aarch64?
