### ISSUE TITLE
Cannot run `qmk` as root

### ISSUE THREAD

**Issue by quisys** [qmk/qmk_cli#26]
```
gentoo ~ # qmk
Traceback (most recent call last):
  File "/home/finn/.local/bin/qmk", line 5, in <module>
    from qmk_cli.script_qmk import main
ModuleNotFoundError: No module named 'qmk_cli'
```

**Comment by skullydazed** [comment]
It looks like you've installed it locally (specific to your user) but are trying to run it as root in an unclean environment, like when using `su` instead of `su -`. You will need to install it as root to run it as root.

Note- it's probably not a good idea to run this as root. I don't think we have any security vulnerabilities, but the potential attack surface is very large.
